# version: "3.9"
version: "3.0"
services:

  gogin-app:
    image: cybernetor066/gogin_app_image:v1.0
    ports:
      - "8080:8080"
    depends_on:
      - redis_server

  redis_server:
    image: "redis:latest"
    ports:
      - "6379:6379"
