---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogin-app
  # namespace: go-app-autoscaling
  labels:
    app: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 1
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: gogin-app
          image: img171422/gogin_app_image:v1.0
          ports:
            - containerPort: 8080

          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
