---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogin-app
  namespace: go-app-autoscaling
  labels:
    app: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 1
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: gogin-app
          image: cybernetor066/gogin_app_image:v1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
