---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "goginapp-hpa"
  namespace: "go-app-autoscaling"
  labels:
    app: "gogin-hpa-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "gogin-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 10
