---
apiVersion: v1
kind: Service
metadata:
  name: gogin-redis-service
  namespace: go-app-autoscaling
spec:
  selector:
    app: goginapp-redis-server
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
