---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "redis-server-hpa"
  namespace: "go-app-autoscaling"
  labels:
    app: "redisserver-hpa-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "gogin-redis-server"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
